### PR TITLE
Release/19.1.1+laterpay2

### PR DESCRIPTION
**Pull request by jdelic**
@doismellburning Here is the change we're deploying, probably not really worth merging into laterpay/gunicorn@master. I prepared the PR sans version change in [feature/921-ignore-async-handle_request-socket-error](https://github.com/laterpay/gunicorn/compare/feature/921-ignore-async-handle_request-socket-error?expand=1) to benoitc/gunicorn.

Once you approve this, I'll file PRs against everything that uses gunicorn for testing and push -laterpay2 to pypi.laterpay.net.

### CODE REVIEW

**Comment by doismellburning** [comment]
Is the "+ in branch name, - in version spec" deliberate?

**Comment by doismellburning** [comment]
(From reading PEP440 a few times, I believe we want +)

**Comment by jdelic** [comment]
+ is in the  branch name because that's what PEP-440 likes. - is in the version specifier because pip does not recognize the +. Which I only found out after extensive fiddling and I got tired of renaming the branch all the time after the gunicorn guys said they'd get a release out with this fix weeks ago :)

**Comment by doismellburning** [comment]
You're supposed to be on holiday! Go holiday!

(but thanks)

**Comment by doismellburning** [comment]
And now all fixed upstream, yay! :)

**Pull request closed without merging**
