### PR TITLE
+ not - for post-version tags

### PR DESCRIPTION
**Pull request by doismellburning**
(retarget as appropriate)

### CODE REVIEW

**Comment by jdelic** [comment]
this will not work because pip doesn't parse `+` in versions correctly, because pip versioning sucks. As the whole gunicorn version fix is one that will go away once gunicorn releases 19.2 I don't see why we'd merge this.

**Comment by doismellburning** [comment]
Pip does; you may be running an old pip which doesn't.

What do you mean "and it'll break"?

**Comment by jdelic** [comment]
> and it'll break

By that I mean: LaterPay RTE runs Python 2.7.6 (a 2.7.9 update is in the works) and that has pip 1.5.6 so it'll break all over the place, for example: Jenkins.

**Comment by doismellburning** [comment]
Right, you mean the LaterPay RTE ships with an old pip

**Comment by doismellburning** [comment]
Mmmh, probably not worth explicitly specifying a setuptools/pip version in the requirements, but tempting...

**Pull request closed without merging**
